Feature/header
deco-sites/brandili pull request #1
Opened 2024-04-19 21:58 UTC by Willians-CMathias

tarefa: https://socialdigitalcommerce.atlassian.net/browse/SWDEV-2262

2024-04-22 20:47 UTC, vmedeirossocial requested changes

2024-04-22 20:47 UTC, vmedeirossocial commented on components/header/Searchbar.tsx
>    return (
A condicional para o o retorno do componente pode ser dessa forma:
```suggestion
  return searchbar &&(
```
ou também:
```suggestion
  return searchbar ? (
  ...
  ) : null
```

2024-04-22 20:47 UTC, vmedeirossocial commented on components/header/Navbar.tsx
>      return (
A condicional pode ser transformada em ternário para o retorno do componente:
```suggestion

return (device === "mobile" || device === "tablet") && (
```

2024-04-22 20:47 UTC, vmedeirossocial commented on components/header/Navbar.tsx
>    return (
No caso do header desktop, ele pode ser o ELSE do seu ternário para o retorno do componente, ficando dessa forma:
```suggestion

  // Desktop header
  ...
  ) : (
  conteúdo do componente de header desktop
  )
```

2024-04-22 20:47 UTC, vmedeirossocial commented on components/header/Menu.tsx
> +  console.log(item);
Remover console.log

2024-04-22 20:47 UTC, vmedeirossocial commented on components/header/TopBar.tsx
> +    return (
A condicional pode ser adicionada ao return do componente com ternário, ficando dessa forma:
```suggestion
   return (device === "mobile") ? (
```

2024-04-22 20:47 UTC, vmedeirossocial commented on components/header/TopBar.tsx
> +      <div className="flex">
No caso do header desktop, ele pode ser o ELSE do seu ternário para o retorno do componente, ficando dessa forma:
```suggestion
  // Desktop header
  ...
  ) : (
  conteúdo do componente de header desktop
  )
```

2024-04-24 11:59 UTC, Willians-CMathias commented on components/header/Menu.tsx
> +  console.log(item);
@vmedeirossocial Corrigido

2024-04-24 11:59 UTC, Willians-CMathias commented on components/header/Searchbar.tsx
>    return (
@vmedeirossocial Corrigido

2024-04-24 11:59 UTC, Willians-CMathias commented on components/header/Drawers.tsx
> +// import { headerHeightMobile } from "./constants.ts";
@vmedeirossocial Corrigido

2024-04-24 17:49 UTC, vmedeirossocial approved these changes

2024-04-24 18:02 UTC, Willians-CMathias commented on components/header/TopBar.tsx
> +    return (
corrigido

2024-04-24 18:40 UTC, vmedeirossocial approved these changes

2024-04-24 18:50 UTC, merged